Repository kubernetes-sigs/e2e-framework, pull requests merged in 2021-07, with the labels that each got.

#22 add testenv unit tests passing context values
  pkg/env/env_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M

#23 remove random file named 1
  1
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/S

#30 Migrating design docs
  .gitignore
  docs/design/e2e-environment-design.png
  docs/design/klient-package.md
  docs/design/test-harness-framework.md
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XXL

#27 Rename Res method to Resource
  klient/k8s/resources/main_test.go
  klient/k8s/resources/resources.go
  klient/k8s/resources/resources_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/testing, size/M

#34 Refactor type `Environment` and env `Config` to support new type`klient.Client`
  examples/simple/hello_test.go
  examples/suites/hello2_test.go
  examples/suites/k8s_example_test.go
  klient/client.go
  klient/conf/config.go
  pkg/conf/config.go
  pkg/conf/ctx.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/envconf/config.go
  pkg/envconf/config_test.go
  pkg/envconf/doc.go
  pkg/flags/flags.go
  pkg/internal/types/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XL
