Repository kubernetes-sigs/e2e-framework, pull requests merged in 2021-05, with the labels that each got.

#6 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#7 quick xample playing w client go integration
  examples/suites/k8s_example_test.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#12 Fixed typo error in function name
  pkg/conf/config_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, sig/testing, size/XS
