Repository kubernetes-sigs/e2e-framework, pull requests merged in 2022-02, with the labels that each got.

#107 emeritus bentheelder
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing

#106 updates on golangci-lint and repo-infra
  hack/verify-boilerplate.sh
  hack/verify-golangci-lint.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing

#105 update controller-runtime to 0.11.0 and their dependencies
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, approved, sig/testing, size/L

#115 add github actions/goreleaser to release the lib
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing
