Repository kubernetes-sigs/e2e-framework, pull requests merged in 2022-06, with the labels that each got.

#125 implement k8s resource watch and trigger action based on the events
  docs/design/k8s-resource-watcher.md
  docs/design/test-harness-framework.md
  examples/watch_resources/README.md
  examples/watch_resources/main_test.go
  examples/watch_resources/watch_test.go
  klient/decoder/decoder.go
  klient/k8s/resources/resources.go
  klient/k8s/watcher/watch.go
Labels: size/XL, lgtm, cncf-cla: yes, approved, sig/testing

#140 Fix function call errors in README
  README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#145 docs(readme): fix test example
  README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, needs-ok-to-test

#148 additional test case to validate watch functionality
  examples/watch_resources/watch_test.go
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing

#151 docs: Fix some typos and code examples
  docs/design/klient-package.md
  docs/design/resource-decoding.md
  docs/design/test-harness-framework.md
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing, needs-ok-to-test
