Repository kubernetes-sigs/e2e-framework, pull requests merged in 2022-12, with the labels that each got.

#172 bump kind to 0.17
  support/kind/kind.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#171 enable dependabot scheduled updates
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, approved, sig/testing, ok-to-test, size/S

#181 update k8s dependencies
  examples/pod_exec/envtest_test.go
  go.mod
  go.sum
  klient/k8s/resources/resources.go
  klient/k8s/resources/resources_test.go
Labels: lgtm, cncf-cla: yes, approved, sig/testing, size/L

#168 Support for an e2e-framework kubetest2 tester
  pkg/env/env.go
  third_party/kubetest2/README.md
  third_party/kubetest2/cmd/kubetest2-tester-e2e-framework/main.go
  third_party/kubetest2/go.mod
  third_party/kubetest2/go.sum
  third_party/kubetest2/pkg/tester/e2e-tester.go
  third_party/kubetest2/pkg/tester/e2e-tester_test.go
Labels: size/XL, lgtm, cncf-cla: yes, approved, sig/testing

#184 Adding harshanarayana as review/approver
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing
