Repository kubernetes-sigs/e2e-framework, pull requests merged in 2023-07, with the labels that each got.

#285 Adding file ADOPTERS.md
  ADOPTERS.md
Labels: lgtm, cncf-cla: yes, approved, sig/testing, size/S

#239 Add support for kwok cluster simulator
  examples/kwok/kwok_with_config/kwok-config.yaml
  examples/kwok/kwok_with_config/kwok_test.go
  examples/kwok/kwok_with_config/main_test.go
  pkg/envfuncs/kwok_funcs.go
  support/kwok/kwok.go
Labels: size/XL, lgtm, cncf-cla: yes, approved, sig/testing, ok-to-test

#284 add description feature to test tables
  examples/table/table_test.go
  pkg/env/env.go
  pkg/features/builder.go
  pkg/features/feature.go
  pkg/features/table.go
  pkg/internal/types/types.go
Labels: lgtm, cncf-cla: yes, approved, sig/testing, size/L

#283 Add templates for flux example
  examples/third_party_integration/flux/template/deployment.yaml
  examples/third_party_integration/flux/template/namespace.yaml
  examples/third_party_integration/flux/template/service.yaml
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing, needs-ok-to-test

#297 fix: CreateWithConfig handling empty image
  support/kind/kind.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#294 remove unused random source seeding property
  pkg/env/env.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#299 show stacktrace when panic in env.Setup
  pkg/env/env.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#292 Fix race condition when executing parallel tests, passing context down and back
  examples/crds/envtest_test.go
  examples/dry_run/dry_run_test.go
  examples/multi_cluster/deployment_test.go
  examples/parallel_features/parallel_features_test.go
  examples/pod_exec/envtest_test.go
  examples/third_party_integration/helm/helm_test.go
  hack/test-go.sh
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/main_test.go
  pkg/internal/types/types.go
Labels: lgtm, cncf-cla: yes, approved, sig/testing, ok-to-test, size/L

#246 cluster provider interface definition
  .gitignore
  examples/crds/main_test.go
  examples/custom_env_funcs/main_test.go
  examples/decoder/main_test.go
  examples/every_test_custom_ns/main_test.go
  examples/kind/kind_with_config/main_test.go
  examples/kwok/kwok_with_config/main_test.go
  examples/multi_cluster/deployment_test.go
  examples/multi_cluster/main_test.go
  examples/parallel_features/parallel_features_test.go
  examples/pod_exec/main_test.go
  examples/predefined_env_funcs/main_test.go
  examples/real_cluster/main_test.go
  examples/skip_flags/main_test.go
  examples/sonobuoy/main_test.go
  examples/third_party_integration/helm/main_test.go
  examples/wait_for_resources/main_test.go
  examples/watch_resources/main_test.go
  klient/decoder/decoder_test.go
  klient/decoder/main_test.go
  klient/internal/testutil/setup.go
  klient/k8s/resources/main_test.go
  klient/k8s/resources/resources_test.go
  klient/wait/main_test.go
  klient/wait/wait_test.go
  pkg/envfuncs/kind_funcs.go
  pkg/envfuncs/kwok_funcs.go
  pkg/envfuncs/provider_funcs.go
  support/kind/kind.go
  support/kwok/kwok.go
  support/types.go
  support/utils/command.go
  third_party/helm/helm.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, sig/testing

#298 enable issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, cncf-cla: yes, approved, sig/testing, size/L
