Repository kubernetes-sigs/e2e-framework, pull requests merged in 2023-06, with the labels that each got.

#251 Add condition for checking if a deployment is available
  klient/wait/conditions/conditions.go
  klient/wait/wait_test.go
Labels: lgtm, cncf-cla: yes, approved, sig/testing, ok-to-test, size/S

#276 Bump sigs.k8s.io/controller-runtime from 0.14.6 to 0.15.0
  examples/crds/envtest_test.go
  examples/crds/main_test.go
  go.mod
  go.sum
  klient/client.go
  klient/decoder/decoder.go
  klient/k8s/resources/resources.go
  klient/k8s/resources/resources_test.go
  klient/k8s/watcher/watch.go
Labels: lgtm, cncf-cla: yes, approved, sig/testing, size/L

#278 handle conversion of resource handler options properly between metav1 and controller-runtime
  klient/k8s/resources/resources.go
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing

#279 chore: pkg imported more than once
  examples/pod_exec/envtest_test.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#281 enable linters of examples and update golangci-lint version
  .golangci.yml
  examples/crds/main_test.go
  examples/dry_run/main_test.go
  examples/every_test_custom_ns/main_test.go
  examples/flags/flags_test.go
  examples/pod_exec/envtest_test.go
  examples/real_cluster/main_test.go
  examples/third_party_integration/helm/helm_test.go
  examples/third_party_integration/helm/main_test.go
  examples/watch_resources/watch_test.go
  hack/verify-golangci-lint.sh
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing

#286 enable using kind/helm binaries from non standard location
  support/kind/kind.go
  third_party/helm/helm.go
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing

#287 enable using kind binary from non standard location
  support/kind/kind.go
Labels: lgtm, cncf-cla: yes, approved, size/M, sig/testing
