Repository kubernetes-sigs/e2e-framework, pull requests merged in 2023-11, with the labels that each got.

#344 Add conditions.DaemonSetReady
  klient/wait/conditions/conditions.go
Labels: kind/feature, lgtm, cncf-cla: yes, approved, sig/testing, ok-to-test, size/S

#319 Validate kindConfigFile while configuring Kind cluster
  support/kind/kind.go
  support/kwok/kwok.go
Labels: kind/bug, lgtm, size/XS, cncf-cla: yes, approved, sig/testing, ok-to-test

#349 support/kwok: Print process output due to an error
  support/kwok/kwok.go
Labels: kind/feature, lgtm, size/XS, cncf-cla: yes, approved, sig/testing

#356 Updates on golang / golangci-lint and dependabot
  .github/dependabot.yml
  .github/workflows/release.yml
  go.mod
  hack/verify-golangci-lint.sh
  pkg/envconf/config.go
Labels: lgtm, cncf-cla: yes, kind/cleanup, approved, sig/testing, size/S

#351 Cronjob controller example
  examples/controller_tests/README.md
  examples/controller_tests/testdata/Dockerfile
  examples/controller_tests/testdata/README.md
  examples/controller_tests/testdata/api/v1/cronjob_types.go
  examples/controller_tests/testdata/api/v1/cronjob_webhook.go
  examples/controller_tests/testdata/api/v1/groupversion_info.go
  examples/controller_tests/testdata/api/v1/webhook_suite_test.go
  examples/controller_tests/testdata/api/v1/zz_generated.deepcopy.go
  examples/controller_tests/testdata/cmd/main.go
  examples/controller_tests/testdata/config/certmanager/certificate.yaml
  examples/controller_tests/testdata/config/certmanager/kustomization.yaml
  examples/controller_tests/testdata/config/certmanager/kustomizeconfig.yaml
  examples/controller_tests/testdata/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  examples/controller_tests/testdata/config/crd/kustomization.yaml
  examples/controller_tests/testdata/config/crd/kustomizeconfig.yaml
  examples/controller_tests/testdata/config/crd/patches/cainjection_in_cronjobs.yaml
  examples/controller_tests/testdata/config/crd/patches/webhook_in_cronjobs.yaml
  examples/controller_tests/testdata/config/default/kustomization.yaml
  examples/controller_tests/testdata/config/default/manager_auth_proxy_patch.yaml
  examples/controller_tests/testdata/config/default/manager_config_patch.yaml
  examples/controller_tests/testdata/config/default/manager_webhook_patch.yaml
  examples/controller_tests/testdata/config/default/webhookcainjection_patch.yaml
  examples/controller_tests/testdata/config/manager/kustomization.yaml
  examples/controller_tests/testdata/config/manager/manager.yaml
  examples/controller_tests/testdata/config/prometheus/kustomization.yaml
  examples/controller_tests/testdata/config/prometheus/monitor.yaml
  examples/controller_tests/testdata/config/rbac/auth_proxy_client_clusterrole.yaml
  examples/controller_tests/testdata/config/rbac/auth_proxy_role.yaml
  examples/controller_tests/testdata/config/rbac/auth_proxy_role_binding.yaml
  examples/controller_tests/testdata/config/rbac/auth_proxy_service.yaml
  examples/controller_tests/testdata/config/rbac/cronjob_editor_role.yaml
  examples/controller_tests/testdata/config/rbac/cronjob_viewer_role.yaml
  examples/controller_tests/testdata/config/rbac/kustomization.yaml
  examples/controller_tests/testdata/config/rbac/leader_election_role.yaml
  examples/controller_tests/testdata/config/rbac/leader_election_role_binding.yaml
  examples/controller_tests/testdata/config/rbac/role.yaml
  examples/controller_tests/testdata/config/rbac/role_binding.yaml
  examples/controller_tests/testdata/config/rbac/service_account.yaml
  examples/controller_tests/testdata/config/webhook/kustomization.yaml
  examples/controller_tests/testdata/config/webhook/kustomizeconfig.yaml
  examples/controller_tests/testdata/config/webhook/manifests.yaml
  examples/controller_tests/testdata/config/webhook/service.yaml
  examples/controller_tests/testdata/e2e-test/e2e_test.go
  examples/controller_tests/testdata/e2e-test/main_test.go
  examples/controller_tests/testdata/go.mod
  examples/controller_tests/testdata/go.sum
  examples/controller_tests/testdata/hack/boilerplate.go.txt
  examples/controller_tests/testdata/internal/controller/cronjob_controller.go
  examples/controller_tests/testdata/internal/controller/cronjob_controller_test.go
  examples/controller_tests/testdata/internal/controller/suite_test.go
Labels: kind/documentation, lgtm, cncf-cla: yes, size/XXL, approved, sig/testing
